[2025-07-06 20:23:25,765] ERROR log_exception() L1414 Exception on /aluno [DELETE] - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\flask\app.py L1414
Traceback (most recent call last):
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\flask_openapi3\scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\app.py", line 254, in delete_aluno
    session.query(Aluno).filter(Aluno.id == aluno_id).first()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2759, in first
    return self.limit(1)._iter().first()  # type: ignore
           ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
        params,
        ^^^^^^^
        execution_options={"_sa_orm_load_options": self.load_options},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2241, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2110, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3273, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3297, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
    rec = pool._do_get()
  File "C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 168, in _do_get
    raise exc.TimeoutError(
    ...<4 lines>...
    )
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2025-07-06 20:23:25,791] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:25] "[35m[1mDELETE /aluno?id=3 HTTP/1.1[0m" 500 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:23:27,188] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:27] "GET /alunos HTTP/1.1" 200 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:23:27,190] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:27] "GET /alunos HTTP/1.1" 200 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:23:36,784] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:36] "OPTIONS /aluno?id=3 HTTP/1.1" 200 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:23:36,829] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:36] "DELETE /aluno?id=3 HTTP/1.1" 200 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:23:38,108] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:38] "GET /alunos HTTP/1.1" 200 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:23:39,976] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:39] "GET /alunos HTTP/1.1" 200 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:23:41,736] INFO _log() L97   127.0.0.1 - - [06/Jul/2025 20:23:41] "GET /alunos HTTP/1.1" 200 - - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\venv\Lib\site-packages\werkzeug\_internal.py L97  
[2025-07-06 20:35:38,259] WARNING predict() L105  Erro de validação ao adicionar aluno: Dados de entrada inválidos. Detalhes: 11 validation errors for AlunoSchema
age
  field required (type=value_error.missing)
gender
  field required (type=value_error.missing)
academic_level
  field required (type=value_error.missing)
country
  field required (type=value_error.missing)
avg_daily_usage_hours
  field required (type=value_error.missing)
most_used_platform
  field required (type=value_error.missing)
affects_academic_performance
  field required (type=value_error.missing)
sleep_hours_per_night
  field required (type=value_error.missing)
mental_health_score
  field required (type=value_error.missing)
relationship_status
  field required (type=value_error.missing)
conflicts_over_social_media
  field required (type=value_error.missing) - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\app.py L105 
[2025-07-06 20:35:38,280] WARNING predict() L105  Erro de validação ao adicionar aluno: Dados de entrada inválidos. Detalhes: 11 validation errors for AlunoSchema
age
  field required (type=value_error.missing)
gender
  field required (type=value_error.missing)
academic_level
  field required (type=value_error.missing)
country
  field required (type=value_error.missing)
avg_daily_usage_hours
  field required (type=value_error.missing)
most_used_platform
  field required (type=value_error.missing)
affects_academic_performance
  field required (type=value_error.missing)
sleep_hours_per_night
  field required (type=value_error.missing)
mental_health_score
  field required (type=value_error.missing)
relationship_status
  field required (type=value_error.missing)
conflicts_over_social_media
  field required (type=value_error.missing) - call_trace=C:\Users\leonardo.romariz\Documents\addicted-V1.2\Projetinho\backend\app.py L105 
